kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - dotnet restore
      - dotnet build --configuration Release
      # Add any additional build steps or tests here

  - name: publish
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands:
      - dotnet publish --no-restore --configuration Release --output ./publish

  - name: deploy
    image: mcr.microsoft.com/dotnet/aspnet:5.0
    commands:
      - cd ./publish
      # Add deployment commands here, like copying files to a server or container

# You can add additional steps as needed, such as running tests, code analysis, etc.
# Refer to Drone CI documentation for more options and possibilities.
