kind: pipeline
type: docker
name: default

# The trigger section defines when this pipeline should be executed.
trigger:
  event:
    - push
  branch:
    - main

# The steps that will be executed in this pipeline.
steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:7.0  # Use .NET Core 3.1 SDK or replace with a different version if needed.
    commands:
      - dotnet restore  # Restore NuGet packages.
      - dotnet build --configuration Release  # Build the application in Release mode.