# This was just a drone runner testing pipeline
kind: pipeline
type: kubernetes
name: default

# The trigger section defines when this pipeline should be executed.
trigger:
  event:
    - push
    - tag
  branch:
    - main

# The steps that will be executed in this pipeline.
steps:
  - name: print_message
    image: alpine
    commands:
      - echo "This is a custom message to the Drone console."
