kind: pipeline
type: docker
name: default

# The trigger section defines when this pipeline should be executed.
trigger:
  event:
    - push
    - tag
  branch:
    - main

# The steps that will be executed in this pipeline.
steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:6.0  # Use .NET 5.0 SDK or replace with a different version if needed.
    commands:
      - dotnet restore  # Restore NuGet packages.
      - dotnet build --configuration Release  # Build the application in Release mode.

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:6.0  # Use .NET 5.0 SDK or replace with a different version if needed.
    commands:
      - dotnet test --configuration Release --no-restore  # Run tests in Release mode.
